### ISSUE TITLE
Add support for `runs-on: macos-latest` GitHub Actions runner

### ISSUE THREAD

**Issue by SergeyVolynkin** [DataDog/test-visibility-github-action#12]
**Environment details (Operating System, Cloud provider, etc):**
GitHub action with `runs-on: macos-latest`

**Describe what happened:**
The `datadog/test-visibility-github-action@v1.0.7` errors out with
```sh
/Users/runner/work/_temp/76c…8f7.sh: line 31: sha256sum: command not found
/Users/runner/work/_temp/76c…8f7.sh: line 32: return: can only `return' from a function or sourced script
Error: Process completed with exit code 1.
```

**Describe what you expected:**
Works same as `runs-on: ubuntu-latest`

**Steps to reproduce the issue:**
Run GitHub Action with `runs-on: macos-latest`
```
      - name: DataDog Configure Test Visibility
        uses: datadog/test-visibility-github-action@v1.0.7
        with:
          languages: js
          service: test
          api_key: ${{ secrets.DD_API_KEY }}
          site: datadoghq.com
```
