### ISSUE TITLE
Suggestions for running tests via docker container AFTER using this action?

### ISSUE THREAD

**Issue by tcs-cclaflin** [DataDog/test-visibility-github-action#17]
We use self-hosted GHA runners that have the basic docker, git, jq, yq installed. Nothing else is allowed to be installed and most build commands must be ran via a docker container. Any suggestions on how the use this action in conjunction with that requirement?

**Environment details (Operating System, Cloud provider, etc): Rocky Linux running self hosted runner**

What I have so far:

```
jobs:
  datadog-test-visibility:
    runs-on: self-hosted
    name: Configure Datadog Test Visibility
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure Datadog Test Visibility
        uses: datadog/test-visibility-github-action@v1.0.9
        with:
          languages: java
          service: test-app-name
          api_key: ${{ secrets.DATADOG_API_KEY }}
          site: datadoghq.com
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Run unit tests
        run: docker run --rm -v $(pwd):/app -w /app -e JAVA_TOOL_OPTIONS=-javaagent:/app/.datadog/dd-java-agent.jar <CUSTOM_JAVA_IMAGE> ./gradlew clean test

```
