### ISSUE TITLE
Early Flake Detection causes vitest to freeze

### ISSUE THREAD

**Issue by TastyPi** [DataDog/test-visibility-github-action#38]
I have no idea how to produce a minimal reproduction. For each branch it seems to randomly pick a specific test service to have issues with, but it consistently gets stuck between retries.

What I have:
- GitHub repository set up with Test Optimization, all options enabled
- Workflow which looks like this:

```yml
name: Test
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read
jobs:
  workspaces:
    runs-on: ubuntu-latest
    name: Workspaces
    outputs:
      workspaces: ${{ steps.workspaces.outputs.workspaces }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          cache: npm
          cache-dependency-path: package-lock.json
      - shell: bash
        run: npm install
      - name: List workspaces
        id: workspaces
        shell: bash
        run: |
          echo "workspaces<<EOF" >> "$GITHUB_OUTPUT"
          npm query '.workspace:has(:attr(scripts, [test]))' | jq -r 'map(.name)' >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

  tests:
    needs: workspaces
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: ${{ fromJSON(needs.workspaces.outputs.workspaces) }}
    name: ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          cache: npm
          cache-dependency-path: package-lock.json
      - shell: bash
        run: npm install
      - uses: datadog/test-visibility-github-action@v2
        with:
          languages: js
          api_key: ${{ secrets.DD_API_KEY }}
          site: datadoghq.eu
          service: ${{ matrix.name }}
      - shell: bash
        run: npm test -w "${{ matrix.name }}"
        env:
          NODE_OPTIONS: -r ${{ env.DD_TRACE_PACKAGE }} --import ${{ env.DD_TRACE_ESM_IMPORT }}

  tests-passed:
    if: ${{ !cancelled() }}
    name: Tests passed
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
```
- The `npm run` script is calling `vitest run --silent`

For each branch, sometimes a random package is "selected" as the "stuck" package. It consistently gets stuck running `npm test`, even when retrying the workflow. The only way to make it unstuck is to go in the Test Optimization settings and disable "Early Flake Detection".
