### ISSUE TITLE
Including DD_TRACE_ESM_IMPORT & DD_TRACE_PACKAGE causes an unsuccessful prisma migrate command in CI

### ISSUE THREAD

**Issue by AnishSDET1** [DataDog/test-visibility-github-action#40]
**Issue**

Including the following in GHA

`NODE_OPTIONS: -r ${{ env.DD_TRACE_PACKAGE }} --import ${{ env.DD_TRACE_ESM_IMPORT }}` causes the following command

**pnpm prisma migrate dev --schema libs/data/src/schema.prisma**

to be `unsuccessful` with no output and therefore `unable to run our unit tests with vitest`.

**NOTE** without `NODE_OPTIONS: -r ${{ env.DD_TRACE_PACKAGE }} --import ${{ env.DD_TRACE_ESM_IMPORT }}` this command works perfectly fine and start logging the migration such as

```
Prisma schema loaded from libs/data/src/schema.prisma
Datasource "db": MySQL database "test_app" at "127.0.0.1:3306"
MySQL database test_app created at 127.0.0.1:3306
Applying migration `20210203112813_init`
Applying migration `20210222120942_remove`
......

```

So there is some kind of issue where including `DD_TRACE_PACKAGE or DD_TRACE_ESM_IMPORT` or both causes prisma commands execution issues i.e. not able to execute these commands.

**Environment**

GHA running on ubuntu

**GHA File**

name: Test
on:

env:
  DD_API_KEY: ${{ secrets.DD_API_KEY }}
jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        app: [test_app]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install dependencies
        run: pnpm install

      - name: Configure Datadog Test Optimization
        uses: datadog/test-visibility-github-action@v2
        with:
          api_key: ${{ env.DD_API_KEY }}
          languages: js
          service: ${{ matrix.app }}
          site: datadoghq.eu

      - name: Run prisma migrate
        run: pnpm prisma migrate dev --schema libs/data/src/schema.prisma
        env:
          NODE_OPTIONS: -r ${{ env.DD_TRACE_PACKAGE }} --import ${{ env.DD_TRACE_ESM_IMPORT }}

**Comment by AnishSDET1** [comment]
Is there any updates on this ?

**Comment by anmarchenko** [comment]
Hi @AnishSDET1! Thank you for contacting us and sorry for the troubles. Our JS library engineer is out of office and will take a look at this issue next week

**Comment by Mariovido** [comment]
Hi @AnishSDET1, this should not be happening. Could you please share the logs of the action (removing sensitive information)? This will help me understand where it is failing. In the meantime, another thing that we can try is running your vitests directly without datadog/test-visibility-github-action (see [instructions](https://docs.datadoghq.com/tests/setup/javascript/?tab=vitest#instrument-your-tests)), and see if that solves the issue.

**Comment by AnishSDET1** [comment]
Thank you for your reply.

For now, it is not an issue with vitests but the command `pnpm prisma migrate dev --schema libs/data/src/schema.prisma` needs to succeed in order to run vitests which is not the case when including `-r ${{ env.DD_TRACE_PACKAGE }} --import ${{ env.DD_TRACE_ESM_IMPORT }}`

There are no logs, as GHA just choses to ignore prisma command when including `-r ${{ env.DD_TRACE_PACKAGE }} --import ${{ env.DD_TRACE_ESM_IMPORT }}` and does not even attempt to execute the command.  And the same behaviour when without `datadog/test-visibility-github-action`.

Very simply, which I have narrowed down, see the 2 cases

WITHOUT `NODE_OPTIONS: '--import dd-trace/register.js -r dd-trace/ci/init'`

```
name: Test
on:
   push:

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: pnpm install

      - name: Run prisma migrate dev command
        run: pnpm prisma migrate dev --schema libs/data/src/schema.prisma
```

The following is reported `Provided --schema at libs/data/src/schema.prisma does not exist` - **NOTE**: I have deliberately deleted file `schema.prisma` as to keep it simple.`.  So here, we have some kind of output.

WITH `NODE_OPTIONS: '--import dd-trace/register.js -r dd-trace/ci/init'`

```
name: Test
on:
   push:

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm prisma migrate dev --schema libs/data/src/schema.prisma
        env:
          NODE_OPTIONS: '--import dd-trace/register.js -r dd-trace/ci/init'
```

**NO OUTPUT** what so ever, so the `pnpm prisma command` is completely ignored when including `NODE_OPTIONS: '--import dd-trace/register.js -r dd-trace/ci/init'`

NOTE: I have also tried executing this command from JS which GHA would call and the same behaviour, where its completely ignored when including these options.

pnpm prisma commands REJECTS node options --import dd-trace/register.js -r dd-trace/ci/init for some reason.

NOTE: To reproduce this, a simple JS Node project can be created with node v20, pnpm (>=9.0.0), @prisma/client(4.16.12), prisma (4.16.2) dependencies and that GHA file, and then to execute the GHA file.

Please advice.

**Comment by AnishSDET1** [comment]
I have created a very small repro so it can be easily reproduced that shows the 2 cases

- WITHOUT NODE_OPTIONS: '--import dd-trace/register.js -r dd-trace/ci/init' - error reported schema does not exist.

- WITH NODE_OPTIONS: '--import dd-trace/register.js -r dd-trace/ci/init' NO OUTPUT what so ever, so prisma command is completely ignored when including NODE_OPTIONS: '--import dd-trace/register.js -r dd-trace/ci/init' - This needs debugging or fixing in dd-trace such that the command is executed and shows the same error as case 1

Shall I attach the small repro zip file ?

**Comment by Mariovido** [comment]
Hi @AnishSDET1 if you can attach the small repro (In a public repository), I would appreciate, as will make our investigating much faster.

**Comment by AnishSDET1** [comment]
Hi there, I will attach the zip file here as its a very small zip file, run the GHA file with & without node options and see the differences as stated above.

[repro-datadog-main.zip](https://github.com/user-attachments/files/20099862/repro-datadog-main.zip)

**Comment by Mariovido** [comment]
@AnishSDET1, could you create a public repo with the information of that zip? We are not allowed to work with this type of files.

**Comment by AnishSDET1** [comment]
@Mariovido The public repro is at https://github.com/rbs-path/repro-datadog

Thanks

**Comment by Mariovido** [comment]
Hi @AnishSDET1,
Sorry but I am bit confused. Does the `pnpm prisma migrate dev --schema libs/data/src/schema.prisma` command run any test? The `NODE_OPTIONS` should be put in the tests not in the prisma command. The workflow should be something like this:
```
...
      - name: Run migrations
        run: pnpm prisma migrate dev --schema libs/data/src/schema.prisma
      - name: Run tests
        shell: bash
        run: pnpm test:vitest
        env:
          NODE_OPTIONS: -r ${{ env.DD_TRACE_PACKAGE }} --import ${{ env.DD_TRACE_ESM_IMPORT }}
...
```

**Comment by AnishSDET1** [comment]
Yes I know, the NODE_OPTIONS are not needed when executing the prisma command. 

Our setup of the prisma command and execution of the vitest is done in the same process. So something like

```
     - name: Run tests
        shell: bash
        run: pnpm test:vitest
        env:
          NODE_OPTIONS: -r ${{ env.DD_TRACE_PACKAGE }} --import ${{ env.DD_TRACE_ESM_IMPORT }}
```

which first sets up prima then runs the unit tests.  And this is where the prisma call is not executed due to the DataDog Trace environment variables.

I did think of refactoring our setup, so the prisma is done in a different step followed by vitest step.  But this is going to be a huge effort and not practical.

The underlying issue of including DD_TRACE causes prisma commands to be ignored which needs to be looked at.
